# Generated by Django 4.0.1 on 2022-06-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_links',
            new_name='article_photos',
        ),
    ]
